# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=1)),
                ('end_date', models.DateField(default=1)),
                ('co_ordinator', models.CharField(max_length=500)),
                ('campaign_type', models.CharField(max_length=500)),
                ('email_content', models.TextField()),
                ('sms_content', models.TextField()),
                ('email_subject', models.TextField()),
                ('target_count', models.IntegerField(default=0)),
                ('leads_generated', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AddField(
            model_name='festmodel',
            name='event_type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='festival_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivalapp.festmodel'),
        ),
    ]
