# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0003_auto_20180627_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='festival_name',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='campaign',
            name='festival',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivalapp.festmodel'),
        ),
    ]
